### PR TITLE
Fixed .hxml filename and added global npm command to README

### PR DESCRIPTION
**Pull request by Jarrio**

### CODE REVIEW

**Comment by Gama11** [comment]
It should be noted that the previous `extraparams.hxml` only works on Windows, since the file system is case-insensitive there.

**Comment by markknol** [comment]
Thanks for your suggestion, one question about the PR

This change suggest you need to use `-D uglify_bin` for local installed npm module, which is not the case, why is that?

**Comment by Jarrio** [comment]
When I installed uglify with the recommended command in the README it was not able to find uglify, it was not until I installed it with `-g` that it was able to find it. Maybe the difference is because I'm on linux?

**Comment by Gama11** [comment]
Btw, `--save` seems to be obsolete: https://stackoverflow.com/a/19578808/2631715

**Comment by Gama11** [comment]
Any update on this PR? :)

**Comment by markknol** [comment]
Ì did some changes to it, the recommended way is to do local install using `--save-dev`

**Pull request merged**
